# rag-pgvector/docker-compose.yml

services:
  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:${PYTHONPATH:-}
    volumes:
      - ./backend:/app
    depends_on:
      - s3_db
      - pgvector_db
    networks:
      - app_network

  s3_db:
    image: minio/minio
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./s3_db:/minio
      - s3_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app_network

  pgvector_db:
    build: ./pgvector_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PGVECTOR_DB_NAME}
      - POSTGRES_USER=${PGVECTOR_DB_USER}
      - POSTGRES_PASSWORD=${PGVECTOR_DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  s3_data:
  pg_data:
